apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluentd.fullname" . }}-config-logzio
data:
  logzio.conf: |
    # taken from here: https://app.logz.io/#/dashboard/data-sources/Fluentd
    <match **>
      @type logzio_buffered
      endpoint_url https://{{ .Values.targets.logzio.listener }}?token=#{ENV['LOGZIO_TOKEN']}&type={{ .Values.targets.logzio.log_type }}
      output_include_time true
      output_include_tags true
      http_idle_timeout 10
      <buffer>
          @type memory
          flush_thread_count 4
          flush_interval 3s
          chunk_limit_size 16m      # Logz.io bulk limit is decoupled from chunk_limit_size. Set whatever you want.
          queue_limit_length 4096
      </buffer>
    </match>
