{{- if .Values.targets.logzio.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd.fullname" . }}-logzio-token
type: Opaque
data:
  token: {{ .Values.targets.logzio.token | b64enc | quote }}
{{- end -}}
