apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluentd.fullname" . }}-config-default
data:
  # the default config name is "fluent.conf", NOT "default.conf"
  fluent.conf: |
{{ .Values.config.default | indent 4 }}
