apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd.fullname" . }}
type: Opaque
data:
  superimportant: "OikK"
{{- if .Values.targets.logzio.enable }}
  logzio-token: {{ .Values.targets.logzio.token | b64enc | quote }}
{{- end }}
