apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- if .Values.source.insecureForward.enable }}
    - name: insecureforward
      port: {{ .Values.source.insecureForward.port }}
      targetPort: insecureforward
      protocol: TCP
{{- end }}
  selector:
    app: {{ template "fluentd.name" . }}
    release: {{ .Release.Name }}
