dist: trusty
sudo: false
language: python
python: "2.7"


env:
  HELM=2.9.1
  OS=linux
  ARCH=amd64
  URL=https://storage.googleapis.com/kubernetes-helm/helm
  BUCKET=helm.cognotekt.com
  BUCKET_KEY=charts/

# highly inspired from this: https://is.gd/vc0Zhz
script:
  # fail on first failure ... travis does not do this by default it seems.
  - set -e
  # download and unpack helm
  - mkdir helm
  - cd helm
  - curl -L "${URL}-v${HELM}-${OS}-${ARCH}.tar.gz" | gunzip | tar xvf -
  - mv "${OS}-${ARCH}/helm" .
  - cd ..
  # lint everything
  - helm/helm lint charts/*
  - helm/helm init --client-only
  # prepare target directories
  - mkdir -p ./public
  - "echo -e 'User-Agent: *\nDisallow: /' > ./public/robots.txt"
  - pip install awscli urllib3[secure]

  # Store current index.yaml as we need to merge it to the new one (to keep older versions)
  - mkdir -p ./merge
  - aws s3 cp s3://helm.cognotekt.com/charts/index.yaml ./merge
  - aws s3 ls s3://${BUCKET}/
  # second - upload
  # create / fill repo
  - helm/helm package charts/* --destination ./public
  - helm/helm repo index --url http://${BUCKET}/${BUCKET_KEY} --merge ./merge/index.yaml ./public/


    #  - '[[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = false ]] && aws s3 sync public/ s3://${BUCKET}/${BUCKET_KEY}'

notifications:
    email:
        on_failure: always
