name: c11h-gitlab-spot-runner
version: 0.1.0
appVersion: 11.11.0-rc1
description: GitLab Spot Runner
keywords:
- ci
- deploy
- docker-machine
- git
sources:
- https://docs.gitlab.com/runner/
maintainers:
- name: OPS Team
  email: ops-team@cognotekt.com
