{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  {{- $root := . -}}
  {{- range .Values.secret.entries }}
  {{- $name := .name }}
  {{ .name }}: {{ if .value -}}
      {{ .value -}}
    {{- else -}}
      {{ index $root.Values $name -}}
    {{- end }}
  {{- end }}
{{- end }}
