{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.metrics.enabled }}
    metrics: "true"
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol:  {{ .protocol | default "TCP" }}
      name: {{ .name }}
  {{- end }}
  {{- if .Values.service.metrics.enableMetricsServicePort }}
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.targetPort }}
  {{- end }}
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
{{- end }}
