{{- if .Values.serviceAccountName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::026861505133:role/{{ toYaml .Values.serviceAccountName }}"
  name: {{ toYaml .Values.serviceAccountName }}
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.label" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
