# The purpose of this file is to annotate configuration options for the c11h-job starter chart.

# Name is very important as it is used for labeling all resources. PLEASE override.
name: "c11h-job"

# podAnnotations:
#   iam.amazonaws.com/role: c11h-team-pod-annotation

## Custom extra labels for the job
# labels:
#   foo: "bar"

restartPolicy: "OnFailure"
completions: "1"


image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

  env:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#envvar-v1-core
    # - name: ENV_NAME
    #   valueFrom:
    #   value:

  # Sets the userid of the main process in the container. Regular users start at 1000, root means 0
  # Running as root is discouraged and not allowed when running restricted pod security policies
  runAsUser: 1000

resources: {} # From Helm:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

secret:
  enabled: false

configMap:
  enabled: false
