# We start with an almost empty values file because we would otherwise
# declare a component with an actual name that could not get removed again.
# Please look in the example folder for populated values files
#components:
#  replaceme:
#    serviceAccountName: "serviceaccount" # Used for IRSA
#    name: "replaceme"
#    replicaCount: 1
#
#    containers:
#      replaceme-service:
#        name: "replaceme-service"
#        image:
#          repository: "026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-team-service/replaceme"
#          pullPolicy: Always
#          runAsUser: 0
#        env:
#          - name: BLA_ENV
#            value: "http://someservice:8080"
#        ports:
#          - name: web
#            containerPort: 8080
#            protocol: TCP
#        resources:
#          limits:
#            cpu: "2"
#            memory: "4Gi"
#          requests:
#            cpu: "500m"
#            memory: "2Gi"

defaults:
  autoscaling: true
  replicaCount: 1
  rollingUpdate:
    maxSurgeCount: 1
    maxUnavaliableCount: 0
  image:
    pullPolicy: IfNotPresent
    runAsUser: 1000
    tag: latest

## For multiple containers
#containers:
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-foobar
#  imagePullPolicy: IfNotPresent
#  name: container1
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-toor
#  imagePullPolicy: IfNotPresent
#  name: container2
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000`
