# We start with an almost empty values file because we would otherwise
# declare a component with an actual name that could not get removed again.
# Please look in the example folder for populated values files
name: "my-empty-system"

defaults:
  autoscaling: true
  replicaCount: 1
  rollingUpdate:
    maxSurgeCount: 1
    maxUnavaliableCount: 0
  image:
    pullPolicy: IfNotPresent
    runAsUser: 1000
    tag: latest

## For multiple containers
#containers:
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-foobar
#  imagePullPolicy: IfNotPresent
#  name: container1
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-toor
#  imagePullPolicy: IfNotPresent
#  name: container2
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000`
