# We start with an almost empty values file because we would otherwise
# declare a component with an actual name that could not get removed again.
# Please look in the example folder for populated values files
defaults:
  autoscaling: true
  replicaCount: 1
  runAsUser: 1000
  rollingUpdate:
    maxSurgeCount: 1
    maxUnavaliableCount: 0
  image:
    pullPolicy: IfNotPresent
    tag: latest

#components:
#  replaceme:
## Role to assume for IRSA. Should be in following format
#    irsaRoleName: c11h-clustername-irsa-team-stage-svc
#    replicaCount: 1
#
## If you need multiple containers
#
#    containers:
#      replaceme-service:
#        name: "replaceme-service"
#        image:
#          repository: "026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-team-service/replaceme"
#          pullPolicy: Always
#          runAsUser: 0
#        env:
#          - name: BLA_ENV
#            value: "http://someservice:8080"
#        ports:
#          - name: web
#            containerPort: 8080
#            protocol: TCP
#        resources:
#          limits:
#            cpu: "2"
#            memory: "4Gi"
#          requests:
#            cpu: "500m"
#            memory: "2Gi"
