apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "rabbitmq.common.labels.standard" . | nindent 4 }}
data:
  rabbitmq.conf: |-
    {{- include "rabbitmq.common.tplvalues.render" (dict "value" .Values.configuration "context" $) | nindent 4 }}
  {{- if .Values.advancedConfiguration}}
  advanced.config: |-
    {{- include "rabbitmq.common.tplvalues.render" (dict "value" .Values.advancedConfiguration "context" $) | nindent 4 }}
  {{- end }}
