{{- range .Values.components }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    component: {{ .name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    {{- if .labels }}
{{ toYaml .labels | indent 4}}
    {{- end }}
spec:
  {{- if kindIs "invalid" .replicaCount }}
  replicas: {{ $.Values.defaults.replicaCount }}
  {{- else }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "chart.name" $ }}
      component: {{ .name }}
      release: {{ $.Release.Name }}
  strategy:
    rollingUpdate:
      {{- /* Needed because rendering because checking for .rollingupdate.something
            will crash when .rollingupdate does not exist */}}
      {{- if kindIs "invalid" .rollingUpdate }}
      maxSurge: {{ $.Values.defaults.rollingUpdate.maxSurgeCount }}
      maxUnavailable: {{ $.Values.defaults.rollingUpdate.maxUnavaliableCount }}
      {{- else }}
        {{- /* We cant use "default" here because '0' (a valid number) is evaluated
              as false a the default is used. True for all numbers. */}}
        {{- if kindIs "invalid" .rollingUpdate.maxSurgeCount }}
      maxSurge: {{ $.Values.defaults.rollingUpdate.maxSurgeCount }}
        {{- else }}
      maxSurge: {{ .rollingUpdate.maxSurgeCount }}
        {{- end }}
        {{- if kindIs "invalid" .rollingUpdate.maxUnavaliableCount }}
      maxUnavailable: {{ $.Values.defaults.rollingUpdate.maxUnavaliableCount }}
        {{- else }}
      maxUnavailable: {{ .rollingUpdate.maxUnavaliableCount }}
        {{- end }}
      {{- end }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "chart.name" $ }}
        component: {{ .name }}
        release: {{ $.Release.Name }}
    {{- if .labels }}
{{ toYaml .labels | indent 8 }}
    {{- end }}
    {{- if .podAnnotations }}
      annotations:
{{ toYaml .podAnnotations | indent 8 }}
    {{- end }}
    spec:
      {{- if .image.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .image.imagePullSecrets }}
      {{- end }}
      {{- if .volumes }}
      volumes:
{{ toYaml .volumes | indent 8}}
      {{- end }}
      {{- if .initContainers }}
      initContainers:
{{ toYaml .initContainers | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Values.defaults.image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default $.Values.defaults.image.pullPolicy }}
          {{- if .securityContext }}
          securityContext:
            capabilities:
              add:
                {{ toYaml .securityContext | indent 8 }}
          {{- end }}
          ports:
          {{- range .image.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: TCP
          {{- end }}
          {{- with .image.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          {{- with .image.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
          {{- end }}
          env:
            {{- range .image.env }}
            - name: {{ .name}}
            {{ if .value }}
              value: {{ quote .value }}
            {{ else if .valueFrom }}
              valueFrom:
              {{ if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                  optional: {{ .valueFrom.secretKeyRef.optional }}
              {{ else if .valueFrom.configMapKeyRef }}
                configMapKeyRef:
                  name: {{ .valueFrom.configMapKeyRef.name }}
                  key: {{ .valueFrom.configMapKeyRef.key }}
                  optional: {{ .valueFrom.configMapKeyRef.optional }}
              {{- end}}
            {{- end}}
            {{- end}}
          securityContext:
            {{- if kindIs "invalid" .image.runAsUser }}
            runAsUser: {{ $.Values.defaults.image.runAsUser}}
            {{ else }}
            runAsUser: {{ .image.runAsUser }}
            {{- end }}
          {{- if .image.volumeMounts }}
          volumeMounts:
{{ toYaml .image.volumeMounts | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .resources | indent 12 }}
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
    {{ end }}
