{{- range .Values.components }}
{{- if .ingress -}}
{{- if .ingress.enabled -}}
{{- $chartName := include "chart.fullname" $ -}}
{{- $componentName := .name -}}
{{- $ingressPath := .ingress.path -}}
{{- $serviceName := .ingress.serviceName -}}
{{- $servicePort := .ingress.servicePort -}}
{{- $additionalPaths := .ingress.additionalPaths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $chartName }}-{{ $componentName }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- with .ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .ingress.tls }}
  tls:
  {{- range .ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              {{- if $serviceName }}
              serviceName: {{ $serviceName }}
              {{- else }}
              serviceName: {{ $chartName }}-{{ $componentName }}
              {{- end }}
              servicePort: {{ $servicePort }}
        {{- range $additionalPaths }}
          - path: {{ .path }}
            backend:
              {{- if .serviceName }}
              serviceName: {{ .serviceName }}
              {{- else }}
              serviceName: {{ $chartName }}-{{ $componentName }}
              {{- end }}
              servicePort: {{ .servicePort | default $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
{{ end }}
