{{- range .Values.components }}
{{- if .ingress -}}
{{- if .ingress.enabled -}}
{{- $fullName := include "chart.fullname" $ -}}
{{- $ingressPath := .ingress.path -}}
{{- $servicePort := .ingress.servicePort -}}
{{- $additionalPaths := .ingress.additionalPaths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- with .ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .ingress.tls }}
  tls:
  {{- range .ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
        {{- range $additionalPaths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .serviceName | default $fullName }}
              servicePort: {{ .servicePort | default $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
{{ end }}
