{{- range .Values.components }}
{{- if .serviceAccountName -}}
{{- $chartName := include "chart.fullname" $ -}}
{{- $componentName := .name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: {{ $chartName }}-{{ $componentName }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "Role"
  name: {{ $chartName }}-{{ $componentName }}
subjects:
- kind: ServiceAccount
  name: {{ toYaml .serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
---
{{ end }}
