{{- $root := . -}}
{{- range .Values.components }}
{{- if .secret -}}
{{- if .secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-secret
data:
  {{- range .secret.entries }}
  {{- $name := .name }}
  {{ .name }}: {{ if .value -}}
      {{ .value | b64enc | quote -}}
    {{- else -}}
      {{ index $root.Values $name | b64enc | quote -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
{{ end }}
