{{- range .Values.components }}
{{- if .service -}}
{{- if .service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.name" $ }}-{{ .name }}
  {{- if .service.annotations }}
  annotations:
  {{ toYaml .service.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    release: {{ $.Release.Name  }}
    heritage: {{ $.Release.Service }}
    {{- if .service.metrics }}
    metrics: "true"
    {{- end }}
spec:
  type: {{ .service.type }}
  ports:
  {{- range .service.ports }}
  - port: {{ .port }}
    targetPort: {{ .targetPort | default .port }}
    protocol:  {{ .protocol | default "TCP" }}
    name: {{ .name }}
  {{- end }}
  {{- if .service.metrics }}
  {{- if .service.metrics.enableMetricsServicePort }}
  - name: metrics
    port: {{ .service.metrics.port }}
    targetPort: {{ .service.metrics.targetPort }}
  {{- end }}
  {{- end }}
  selector:
    component: {{ .name }}
    app: {{ template "chart.name" $ }}
    release: {{ $.Release.Name }}
{{- end }}
{{- end }}
---
{{ end }}
