{{- range .Values.components }}
{{- if .irsaRoleName -}}
{{- $chartName := include "chart.fullname" $ -}}
{{- $componentName := .name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::026861505133:role/{{ toYaml .irsaRoleName }}"
    meta.helm.sh/release-name: {{ template "chart.name" $ }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  name: {{ $.Release.Name }}-{{ $componentName }}
  labels:
    app: {{ template "chart.name" $ }}
    chart: {{ template "chart.label" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/managed-by: helm
{{- end }}
---
{{ end }}
