# The purpose of this file is to annotate configuration options for the c11h-basic starter chart.

# Name is very important as it is used for labeling all resources. PLEASE override.
name: "c11h-basic"
replicaCount: 1

# See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
rollingUpdate:
  maxSurgeCount: 1
  maxUnavaliableCount: 1


## Custom extra labels
# labels:
#   foo: "bar"

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
  # imagePullSecrets: regcred
  # An array of objects partially following this spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#containerport-v1-core
  # hostPort and hostIP not supported
  ports:
    - name: blah
      containerPort: 1234
  env:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#envvar-v1-core
    # - name: ENV_NAME
    #   valueFrom:
    #   value:

service:
  enabled: true
  # Sets a label that identifies the service as ready for Prometheus scraping
  metrics:
    # metrics are collected at the /metrics endpoint
    enabled: false
    # creates a port named metrics on the created service
    # use it when exposing metrics on a different port than
    # application requests
    enableMetricsServicePort: false
    # port is set at the service level
    port: 8080
    # targetPort should be exposed by your pod
    targetPort: 8080
  type: ClusterIP # Only ClusterIP and LoadBalancer are supported.
  # An array of objects following this spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#serviceport-v1-core
  # NodePort unsupported!
  ports:
    # just don't name it metrics or reuse previously set port and targetPort if enabled above
    - name: blah
      port: 1234
      targetPort: 1234

ingress:
  enabled: false
  # Traefik is the recommended ingress controller
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  tls: [] # TLS can be configured manually
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  servicePort: # 8080 Incoming port of service with the SAME name
  # to be set as --set ingress.hosts={a,b,c}
  hosts: {}
  # 1 host -> 1 service

vpn:
  enabled: false
  image:
    repository: mysecretregistry/somevpncontainer
    pullPolicy: Always
    tag: latest
  env:

resources: {} # From Helm:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

secret:
  enabled: false

configMap:
  enabled: false

# Also supported:
nodeSelector: {}
tolerations: []
affinity: {}
