# The purpose of this file is to annotate configuration options for the c11h-basic starter chart.

# Name is very important as it is used for labeling all resources. PLEASE override.
name: "c11h-basic"
replicaCount: 1

autoscaling: true

# See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
rollingUpdate:
  maxSurgeCount: 1
  maxUnavaliableCount: 0


## Custom extra labels
# labels:
#   foo: "bar"

# Custom pod annotations
# podAnnotations:
#   foo: "bar"

## Role to assume for IRSA. Should be in following format
# irsaRoleName: c11h-clustername-irsa-team-stage-svc

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
  # imagePullSecrets: regcred
  # An array of objects partially following this spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#containerport-v1-core
  # hostPort and hostIP not supported
  ports:
    - name: blah
      containerPort: 1234
  env:
    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#envvar-v1-core
    # - name: ENV_NAME
    #   valueFrom:
    #   value:
    
  # Sets the userid of the main process in the container. Regular users start at 1000, root means 0
  # Running as root is discouraged and not allowed when running restricted pod security policies
  runAsUser: 1000

service:
  enabled: true
  # Sets a label that identifies the service as ready for Prometheus scraping
  metrics:
    # metrics are collected at the /metrics endpoint
    enabled: false
    # creates a port named metrics on the created service
    # use it when exposing metrics on a different port than
    # application requests
    enableMetricsServicePort: false
    # port is set at the service level
    port: 8080
    # targetPort should be exposed by your pod
    targetPort: 8080
  type: ClusterIP # Only ClusterIP and LoadBalancer are supported.
  # An array of objects following this spec:
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#serviceport-v1-core
  # NodePort unsupported!
  ports:
    # just don't name it metrics or reuse previously set port and targetPort if enabled above
    - name: blah
      port: 1234
      targetPort: 1234
  # annotations:
  #   service.beta.kubernetes.io/fancy-new-aws-feature: true

cronjob:
  enabled: false
  # annotations:
  #   cronjob.beta.kubernetes.io/fancy-new-aws-feature: true
  # The current schedule is set to 7AM to 9PM european summertime
  schedule_up: "* 5 * * 1-5" # use cron-syntax here. The set default here is 5AM from monday to friday (UTC)
  schedule_down: "* 19 * * 1-5" # use cron-syntax here. The set default here is 7PM from monday to friday (UTC)
  max_count: 1 # count of replicas for scale up
  min_count: 0 # count of replicas for scale down

ingress:
  enabled: false
  # Traefik is the recommended ingress controller
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  tls: [] # TLS can be configured manually
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  servicePort: # 8080 Incoming port of service with the SAME name
  # to be set as --set ingress.hosts={a,b,c}
  hosts: {}
  # 1 host -> 1 service
  additionalPaths: []
  #  - path: /path
  #    serviceName: name  # defaults to the name of this service
  #    servicePort: 123   # defaults to .Values.ingress.servicePort

resources: {} # From Helm:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

secret:
  enabled: false

configMap:
  enabled: false

# Also supported:
nodeSelector: {}
tolerations: []
affinity: {}

## For multiple containers
#containers:
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-foobar
#  imagePullPolicy: IfNotPresent
#  name: container1
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000
#- env:
#  - name: SOMEVAR
#    valueFrom:
#      secretKeyRef:
#        key: secret-key
#        name: keyname
#  image: 026861505133.dkr.ecr.eu-central-1.amazonaws.com/c11h-toor
#  imagePullPolicy: IfNotPresent
#  name: container2
#  ports:
#  - containerPort: 1234
#    name: blah
#    protocol: TCP
#  resources:
#    limits:
#      cpu: 100m
#      memory: 384M
#    requests:
#      cpu: 100m
#      memory: 384M
#  securityContext:
#    runAsUser: 1000

