apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4}}
    {{- end }}
spec:
  template:
    {{- if .Values.podAnnotations }}
    metadata:
      annotations:
{{ toYaml .Values.podAnnotations | indent 10 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.image.env }}
            - name: {{ .name}}
            {{ if .value }}
              value: {{ quote .value }}
            {{ else if .valueFrom }}
              valueFrom:
              {{ if .valueFrom.secretKeyRef }}
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
                  optional: {{ .valueFrom.secretKeyRef.optional }}
              {{ else if .valueFrom.configMapKeyRef }}
                configMapKeyRef:
                  name: {{ .valueFrom.configMapKeyRef.name }}
                  key: {{ .valueFrom.configMapKeyRef.key }}
                  optional: {{ .valueFrom.configMapKeyRef.optional }}
              {{- end}}
            {{- end}}
            {{- end}}
          securityContext:
            runAsUser: {{ .Values.image.runAsUser }}
      restartPolicy: {{ .Values.restartPolicy }}
  completions: {{ .Values.completions }}
