apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.label" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4}}
    {{- end }}
spec:
  template:
    {{- if .Values.podAnnotations }}
    metadata:
      annotations:
{{ toYaml .Values.podAnnotations | indent 10 }}
      {{- end }}
    spec:
      {{ if .Values.irsaRoleName }}
      serviceAccountName: {{ .Release.Name }}
      {{ end }}
      {{ if .Values.initContainer }}
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          env: {{- include "helpers.list-env-variables" . | indent 14 }}
          securityContext:
            runAsUser: {{ .Values.initContainer.runAsUser }}
          resources:
{{ toYaml .Values.initContainer.resources | indent 12 }}
      {{- end }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.container.repository }}:{{ .Values.container.tag }}"
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          env: {{- include "helpers.list-env-variables" . | indent 14 }}
          securityContext:
            runAsUser: {{ .Values.container.runAsUser }}
          resources:
{{ toYaml .Values.container.resources | indent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}
  completions: {{ .Values.completions }}
